name: Deploy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir secreto
        run: echo "Valor del secreto es ${{ secrets.TOKEN_SECRET }}"

      - name: Imprimir variable de entorno
        run: echo "Valor de la variable es ${{ vars.NAME }}"

  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Instalar dependencias
        run: npm install

      - name: Run test
        run: npm run test

  deploy_job:
    runs-on: ubuntu-latest
    needs: build_job

    steps:
      - name: Deploy
        run: echo "Deploy..."

  report_job:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: deploy_job

    steps:
      - name: Deploy
        run: echo "Enviando reportes..."
