name: Deploy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir secreto
        run: echo "Valor del secreto es ${{ secrets.TOKEN_SECRET }}"

      - name: Imprimir variable de entorno
        run: echo "Valor de la variable es ${{ vars.NAME }}"

  build_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup
        uses: actions/setup-node@v5
        with:
          node-version: "24"

      - name: Instalar dependencias
        run: npm install

      - name: Run test
        run: npm run test

      - name: Build page
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public/

  deploy_job:
    runs-on: ubuntu-latest
    needs: build_job

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment-pages.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment-pages
        uses: actions/deploy-pages@v4

  notify_job:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: deploy_job

    steps:
      - name: Notify to Slack
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TOKEN_SLACK }}
        with:
          status: ${{ job.status }}
